# Generated by Django 4.2.2 on 2023-06-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNomads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viaje',
            new_name='Viajes',
        ),
    ]
